### ISSUE TITLE
Switching images does not work

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Images#104]
### Steps to reproduce

1. Start People `develop` branch, Images `develop` branch, SignIn `develop` branch
2. Go to http://localhost:8080/signin/generateadminuser to generate your admin user
3. Go to http://localhost:8080/signin/signinuser and sign in as admin/admin
4. Go to http://localhost:8080/people/persons and click on "Edit" button next to a person
5. Scroll down to add a new image for that person. Upload your first image
6. Press "+" button and add another image. Upload your second image
7. Press "Save"
8. Click on the two images to switch between them

### Expected result

Clicking on image thumbnails should switch between images

### Actual result

Nothing happens in the view, error in the Chrome console:

```
Uncaught ReferenceError: Invalid left-hand side expression in prefix operation
    at HTMLTemplateElement.template.onPreviewClick (<anonymous>:7:63)
    at handler (polymer.html:507)
    at HTMLImageElement.decorated (polymer.html:4464)
```

##### Involved apps' version

StarcounterApps/SignIn@29ecd3e550c60d19b9298b556a2e430e4d50ccea
StarcounterApps/People@a675e2fd0457355549a31a83bfe2a813b8a7b04d
StarcounterApps/Images@d94326f34f874854d41c99cc9c0a2e038f051158
 
##### Browsers affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Screenshot

![2017-06-23 12_54_04-people](https://user-images.githubusercontent.com/566463/27479332-d7d7c158-5813-11e7-87a5-2ea41fa0011a.png)

**Comment by Mihaiii** [comment]
Made PR #107 as a propose solution.

**Comment by Mihaiii** [comment]
Closing as fixed.
