### ISSUE TITLE
Add comments in code that explain the usage of the Authorization library

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Images#113]
As discussed in https://github.com/StarcounterApps/Website/issues/123, add comments in code that explain the usage of the [Authorization](https://github.com/Starcounter/authorization) library in this app.

**Comment by un-tone** [comment]
Created PR https://github.com/StarcounterApps/Images/pull/115

**Comment by warpech** [comment]
Quick Reply<sup>[?](https://github.com/warpech/QuickReply)</sup>: Closing as done.
