### ISSUE TITLE
Apply BEM to Images's private CSS

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Images#24]
This app contains globally applied CSS rules in stylesheets: 
- https://github.com/StarcounterSamples/Images/blob/b43bd368926e0b20e0d211a1b7ac6c1753a7d835/src/Images/wwwroot/Images/css/standalone.css

It also contains inline CSS in HTML templates: 
- https://github.com/StarcounterSamples/Images/blob/master/src/Images/wwwroot/Images/viewmodels/ImagesPage.html
- https://github.com/StarcounterSamples/Images/blob/master/src/Images/wwwroot/Images/viewmodels/PreviewPage.html

All private CSS should be converted to BEM-style CSS classes defined in a stylesheet, according to the intent started in the issue https://github.com/Starcounter/Starcounter/issues/3450 and explained in the article http://starcounter.io/guides/web/avoiding-css-conflicts/

**Comment by Mnosek** [comment]
Also in PreviewPage.html the class `chatter-img-thumbnail`should be renamed according to application name.

**Comment by mmnosek** [comment]
+1, we need it in SWO project.

**Comment by diliger** [comment]
PR #81

**Comment by diliger** [comment]
Merged. Close.
