### ISSUE TITLE
Video support

### ISSUE THREAD

**Issue by aloscha** [StarcounterApps/Images#54]
As we start to support video, we should have opportunity to add it from main view.
Now we don't have this opportunity

![image](https://cloud.githubusercontent.com/assets/5141943/19851624/2042c08c-9f5f-11e6-9272-0d0694652a30.png)

I think there should be button, add video or instead of Add Image should be Add media.
Also Video support should be clickable in Settings of app

**Comment by diliger** [comment]
do you mean I should add another option in settings to enable or disable videos in the app?

**Comment by aloscha** [comment]
IMHO yes, like SupportVideo: yes/no
Because I get that we have partial for that, but If we can add that functionality for `free` why not

**Comment by aloscha** [comment]
@diliger 
I think we should provide settings - enable media control - on/off
And if on, we have button `add video` with providing adding video

**Comment by warpech** [comment]
@diliger, can this issue be closed now?

**Comment by diliger** [comment]
@warpech, no, it requires some rework, do you confirm the idea @aloscha described?

**Comment by warpech** [comment]
I don't understand it fully. Isn't it that right now, drag and drop as well as file upload button support both images and videos upload in all partials?

**Comment by warpech** [comment]
I don't think that a global setting "support videos" makes sense. In the complete system I might want to use videos in one context, videos and images in another context, and only images in 3rd context.

**Comment by aloscha** [comment]
Sorry guys, it works like I want, but have few mistakes

1. Clear button doesn't work
![image](https://cloud.githubusercontent.com/assets/5141943/23557291/e5e594e6-002f-11e7-9a6d-04e632bbb39e.png)

2. Add 'Image' is a bit confusing. Maybe renaming it into `Media`

**Comment by warpech** [comment]
Point 1 moved to a separate issue: https://github.com/StarcounterApps/Images/issues/78

Point 2 moved to a separate issue: https://github.com/StarcounterApps/Images/issues/79
