### ISSUE TITLE
Clear button doesn't work

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Images#78]
@aloscha reports in https://github.com/StarcounterApps/Images/issues/54#issuecomment-283986872:

> Clear button doesn't work
![image](https://cloud.githubusercontent.com/assets/5141943/23557291/e5e594e6-002f-11e7-9a6d-04e632bbb39e.png)

**Comment by diliger** [comment]
PR #81

**Comment by diliger** [comment]
Merged.

**Comment by warpech** [comment]
This is still not fixed. Steps to reproduce:

1. Start Images app
2. Go to http://localhost:8080/images
3. Press "Add image or video" at the bottom of the page
4. Upload an image
5. Press "Clear" button (once).

Works as expected in Chrome.

Fails in Edge and Firefox.

**Comment by diliger** [comment]
All buttons click only with second click in FF, I can replace it with `onmousedown` as in **Chatter** app,
but is that a correct solution?

**Comment by warpech** [comment]
The correct solution is to follow the button patterns presented and tested in KitchenSink, which is the reference for data binding in all other apps.

So - yes :)

**Comment by diliger** [comment]
PR #96

**Comment by warpech** [comment]
Closing as done
