### ISSUE TITLE
Change the text on "Add image" button

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Images#79]
@aloscha proposes in https://github.com/StarcounterApps/Images/issues/54#issuecomment-283986872:

> Add 'Image' is a bit confusing. Maybe renaming it into `Media`

I propose to rename the text on the button to "Add image or video"

This is the line: https://github.com/StarcounterApps/Images/blob/3761050dd8cbbe993de8426798a7f1a4512634c5/src/Images/wwwroot/Images/viewmodels/ImagesPage.html#L42

**Comment by diliger** [comment]
PR #81

**Comment by diliger** [comment]
Merged.

**Comment by warpech** [comment]
Closing as fixed
