### ISSUE TITLE
Cannot upload an image when a page is loaded over https

### ISSUE THREAD

**Issue by mmnosek** [StarcounterApps/Images#98]
### Steps to reproduce
1. Run app that uses Images
2. Run Images
3. Load a page over https
4. Try to upload some image

### Expected result
Image is uploaded in the same way as by https

### Actual result
An image is not uploaded and an error in browser console occurs:
```
webSocket connection to 'wss://test-sweoffshore.mysampleapp.com/images/images?filesize=16933&sessionid=8D74030DE1CA744E10000010&filename=1219066.png&filetype=image/png' failed: Error during WebSocket handshake: Unexpected response code: 404
starcounter-upload.html:234 Socket error:  {"isTrusted":true}
```

##### Browsers affected
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

cc @warpech

**Comment by warpech** [comment]
@un-tone, could you pls investigate this? This is high priority now

**Comment by un-tone** [comment]
This solution https://github.com/socketio/socket.io/issues/1942#issuecomment-82352072 must help with the issue. I checked it on my local machine.
Thanks @mmnosek for help

**Comment by mmnosek** [comment]
Well, looks very promising but I can't make it work on my server. I've changed a config and now I got 500 error code in the console. @un-tone probably I'm missing something, could you please have a look at the config I've sent you and make adjustments? Thanks!

After that, we need also to include our solution here: https://docs.starcounter.io/guides/working-with-starcounter/using-https-on-nginx/ of course together with explanation :) I will take care of it.

**Comment by un-tone** [comment]
Please check this https://gist.github.com/un-tone/e0411dd6ba90f01c3e0bbac8b2c7d522

**Comment by un-tone** [comment]
There is another issue https://github.com/Starcounter/starcounter-upload/issues/8

**Comment by un-tone** [comment]
The original issue is resolved. It remains only to add info to https://docs.starcounter.io/guides/working-with-starcounter/using-https-on-nginx/

**Comment by warpech** [comment]
Thanks guys! 

@mmnosek can you pls make a new issue in Starcounter/Docs and close this issue?

**Comment by mmnosek** [comment]
All included here: https://github.com/Starcounter/Docs/issues/54 thanks @un-tone !
